### PR TITLE
add aria-label to button

### PR DESCRIPTION
**Pull request by mdulat**

### CODE REVIEW

**Comment by dlockhart** [comment]
Hey @mdulat, what's the reasoning for adding this? We're actually in the process of deprecating `image-action-button` and replacing it with the new [subtle button](http://design.d2l/components/buttons/) pattern.

**Comment by mdulat** [comment]
We're actually using these as icon-only buttons, so the aria-label needs to be passed down so that it can be added to the button tag. It looks like d2l-button-icon might work though, as it already has the "text" property that sets the aria-label. If we're deprecating image-action-button, I'll try replacing it with d2l-button-icon in our app, will let you know how it works out.

**Comment by dlockhart** [comment]
OK cool, so in that case, @margaree has just built `<d2l-button-icon>`, which is meant exactly for that use case -- buttons that are icon-only. They look like this:

screen shot 2018-05-08 at 5 03 50 pm

**Comment by mdulat** [comment]
Ok so just chatting with my product manager. We are planning on updating all our buttons for 1807, so were hoping we can get this fix in to solve a current accessibility issue for 1806 (rather than updating the buttons now). Would this change be ok to merge in for this temporary fix?

**Comment by dlockhart** [comment]
I'd rather not muddy up `image-action`'s API if we can avoid it, which I think we can. How about instead of your change, you just do this:

    <d2l-image-action-button icon="icon"><d2l-offscreen>Label for button</d2l-offscreen></d2l-image-action-button>

The `<d2l-offscreen>` component positions the text off the screen so that it's invisible to visual users but available to screen readers.

**Comment by mdulat** [comment]
Yes <d2l-offscreen> does the job. Thanks Dave, I'll close this PR then.

**Pull request closed without merging**
