### PR TITLE
Mbayly/propagate focus blur

### PR DESCRIPTION
**Pull request by mdgbayly**
Fire custom focus/blur events from d2l-image-action-button when the custom element or internal button are focused/blurred.

### CODE REVIEW

**Comment by dbatiste** [comment]
Perhaps we should be adding to [d2l-focusable-behavior](https://github.com/Brightspace/d2l-polymer-behaviors-ui/blob/master/d2l-focusable-behavior.html#L12)?  I think we (I) may have omitted this since it was not clear that is was needed.

**Comment by dlockhart** [comment]
Yeah, seems like a really worthwhile addition to `focusable-behavior`.

Also, @mdgbayly just as an FYI: with the upcoming changes to buttons to align better with the new button styles, the `image-action` component in its entirety is going to be deprecated. It'll stick around obviously, but it will be replaced by the new "subtle" button styles. This work is a couple weeks out.

**Comment by mdgbayly** [comment]
Regarding d2l-focusable-behavior. Yes - I could add it. I saw there was a comment in there to keep it bare bones for now. But happy to add it if you think it would be a better solution. 

Regarding deprecation  - yep understood - we use these buttons in a few places - we're just trying to get updated to the latest version of all the button elements as part of our Polymer 2 hybridization prep work. But realize we'll have to do another pass at the buttons when the new subtle buttons are out.

**Comment by mdgbayly** [comment]
FYI - tests will fail until we merge/bump https://github.com/Brightspace/d2l-polymer-behaviors-ui/pull/19

**Pull request merged**
